<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1689779752225' stop='1689779794651'>
    <name>Scenario1 </name>
    <title>Scenario1 </title>
    <test-cases>
        <test-case start='1689779752226' status='broken' stop='1689779794645'>
            <name>Testing Scenario 1</name>
            <title>Testing Scenario 1</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>`cy.visit()` failed trying to load:
                
                http://trustoo.nl:3000/
                
                We attempted to make an http request to this URL but the request failed without a response.
                
                We received this error at the network level:
                
                  > Error: connect ETIMEDOUT 13.225.78.20:3000
                
                Common situations why this would fail:
                  - you don't have internet access
                  - you forgot to run / boot your web server
                  - your web server isn't accessible
                  - you have weird network configuration settings on your computer
                
                Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Scenario1 `</message>
                <stack-trace>CypressError: `cy.visit()` failed trying to load:
                
                http://trustoo.nl:3000/
                
                We attempted to make an http request to this URL but the request failed without a response.
                
                We received this error at the network level:
                
                  > Error: connect ETIMEDOUT 13.225.78.20:3000
                
                Common situations why this would fail:
                  - you don't have internet access
                  - you forgot to run / boot your web server
                  - your web server isn't accessible
                  - you have weird network configuration settings on your computer
                
                Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Scenario1 `
                    at http://localhost:59004/__cypress/runner/cypress_runner.js:157807:23
                    at visitFailedByErr (http://localhost:59004/__cypress/runner/cypress_runner.js:157162:12)
                    at http://localhost:59004/__cypress/runner/cypress_runner.js:157806:11
                    at tryCatcher (http://localhost:59004/__cypress/runner/cypress_runner.js:10325:23)
                    at Promise._settlePromiseFromHandler (http://localhost:59004/__cypress/runner/cypress_runner.js:8260:31)
                    at Promise._settlePromise (http://localhost:59004/__cypress/runner/cypress_runner.js:8317:18)
                    at Promise._settlePromise0 (http://localhost:59004/__cypress/runner/cypress_runner.js:8362:10)
                    at Promise._settlePromises (http://localhost:59004/__cypress/runner/cypress_runner.js:8438:18)
                    at _drainQueueStep (http://localhost:59004/__cypress/runner/cypress_runner.js:5032:12)
                    at _drainQueue (http://localhost:59004/__cypress/runner/cypress_runner.js:5025:9)
                    at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:59004/__cypress/runner/cypress_runner.js:5041:5)
                    at Async.drainQueues (http://localhost:59004/__cypress/runner/cypress_runner.js:4911:14)
                
                From Node.js Internals:
                  Error: connect ETIMEDOUT 13.225.78.20:3000
                      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
                  </stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>